### ISSUE TITLE
contributions

### ISSUE THREAD

**Issue by calkan** [damlaozgen/SUN#12]
I do not see any commit/contributions from @dilanbilkent @yeLizK and @aertan 
explain.

**Comment by damlaozgen** [comment]
Dear sir, my group members are doing their parts but having difficulties to
commit them to git. Since we are in a rush, I couldn't manage a meeting to
help them but tomorrow I will meet with yeliz, later we will get together
with all group members this monday, commit all the codes and fix some
remaining problems.

**Comment by calkan** [comment]
ok, if there are problems with the Android side, then I will hold them responsible.
